package org.cuong.model;
// Generated Aug 14, 2016 6:25:29 PM by Hibernate Tools 4.3.4.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Max;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;

import org.cuong.validator.isValidName;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "mkyong")
public class Users implements java.io.Serializable {

	private String id;
	@Size(min = 5, max = 10)
	@isValidName(listName = "cuong")
	private String name;
	private String email;
	private String address;
	private String password;
	private Boolean newsletter;
	private String framework;
	private String sex;
	private Integer number;
	private String country;
	private String skill;
	private List<Role> roles = new ArrayList<Role>();
	@Transient
	private ArrayList<String> skillOther;
	@Transient
	@Past
	private Date dateOfBirth;
	@Transient
	private Address address2;
	@Transient
	@Max(2222)
	private Long mobiphone;
	@Transient
	private String signInProvider;

	public Users() {
	}

	public Users(String id, String email) {
		super();
		this.id = id;
		this.email = email;
	}

	public Users(String name, String email, String address, String password, Boolean newsletter, String framework,
			String sex, Integer number, String country, String skill, ArrayList<Role> roles) {
		this.name = name;
		this.email = email;
		this.address = address;
		this.password = password;
		this.newsletter = newsletter;
		this.framework = framework;
		this.sex = sex;
		this.number = number;
		this.country = country;
		this.skill = skill;
		this.roles = roles;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "newsletter")
	public Boolean getNewsletter() {
		return this.newsletter;
	}

	public void setNewsletter(Boolean newsletter) {
		this.newsletter = newsletter;
	}

	@Column(name = "framework", length = 500)
	public String getFramework() {
		return this.framework;
	}

	public void setFramework(String framework) {
		this.framework = framework;
	}

	@Column(name = "sex", length = 1)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "NUMBER")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "COUNTRY", length = 10)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "SKILL", length = 500)
	public String getSkill() {
		return this.skill;
	}

	public void setSkill(String skill) {
		this.skill = skill;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "users_has_role", catalog = "mkyong", joinColumns = {
			@JoinColumn(name = "users_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public List<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	@Transient
	public ArrayList<String> getSkillOther() {
		return skillOther;
	}

	public void setSkillOther(ArrayList<String> skillOther) {
		this.skillOther = skillOther;
	}

	@Transient
	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Override
	public String toString() {
		return "Users [id=" + id + ", name=" + name + ", email=" + email + ", address=" + address + ", password="
				+ password + ", newsletter=" + newsletter + ", framework=" + framework + ", sex=" + sex + ", number="
				+ number + ", country=" + country + ", skill=" + skill + ", skillOther=" + skillOther + ", dateOfBirth="
				+ dateOfBirth + ", address2=" + address2 + ", mobiphone=" + mobiphone + "]";
	}

	@Transient
	public Address getAddress2() {
		return address2;
	}

	public void setAddress2(Address address2) {
		this.address2 = address2;
	}

	@Transient
	public Long getMobiphone() {
		return mobiphone;
	}

	public void setMobiphone(Long mobiphone) {
		this.mobiphone = mobiphone;
	}

	@Transient
	public String getSignInProvider() {
		return signInProvider;
	}

	public void setSignInProvider(String signInProvider) {
		this.signInProvider = signInProvider;
	}

}
